version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/sou-homepage-deploy
    docker:
      - image: circleci/ruby:2.4.1-node
        environment:
          STAGING_URI: http://sumofus-homepage-staging.s3-website-us-west-2.amazonaws.com
          STAGING_BUCKET: sumofus-homepage-staging
    steps:
      - checkout

      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'

      # Restore bundle cache
      - type: cache-restore
        key: sou-homepage-deploy-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: bundle install --path vendor/bundle

      - run:
          name: install-npm-wee
          command: npm install

      # Store bundle cache
      - type: cache-save
        key: sou-homepage-deploy-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
          - ./node_modules

      # Build
      - run: bundle exec middleman build

      - type: shell
        command: |
          ./scripts/deploy.sh

      - type: store_test_results
        path: /tmp/deploy-results
