service: sou-homepage-related

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  region: us-west-2

functions:
  deploy:
    environment:
      CI_TOKEN: ${opt:ci-token}
    handler: functions/prismic.handler
    events:
      - http:
          path: prismic/webhook
          method: post
