service: sou-homepage-related

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs4.3
  region: us-west-2
  environment: ${file(./env.yml)}

functions:
  updateCount:
    handler: functions/count.handler
    events:
      - schedule: rate(1 hour)
  deploy:
    handler: functions/prismic.handler
    events:
      - http:
          path: prismic/webhook
          method: post
