service: sou-homepage-related

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs6.10
  region: us-west-2
  environment: ${file(./env.yml)}
  memorySize: 128
  timeout: 10
  iamRoleStatements:
    -  Effect: "Allow"
       Action: "s3:*"
       Resource:
         - "arn:aws:s3:::sou-homepage-counter/*"
functions:
  updateCount:
    handler: functions/count.handler
    events:
      - schedule: rate(1 hour)
  deploy:
    handler: functions/prismic.handler
    events:
      - http:
          path: prismic/webhook
          method: post
